### ISSUE TITLE
Generated 0 grasp candidates

### ISSUE THREAD

**Issue by chaiban** [atenpas/gpg#10]
I changed multiple parameters and tested it, but I am getting zero grasps. could someone help me with that ? thank you! 
This is what I get after running

finger_width: 0.01
hand_outer_diameter: 0.12
hand_depth: 0.06
hand_height: 0.02
init_bite: 0.01
CFG: Not a valid b received!
voxelize: 1
remove_outliers: 0
workspace: -1.0 1.0 -1.0 1.0 -1.0 1.0
camera_pose: 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
num_samples: 5
num_threads: 4
nn_radius: 0.001
num_orientations: 1
rotation_axis: 2
plot_grasps: 1
plot_normals: 1
Loaded point cloud with 1319524 points 
3
Processing cloud with: 1319524 points.
After workspace filtering: 0 points left.
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
Estimating local reference frames ...
Error: No samples or no indices!
Generated 0 grasp candidate sets.
Generated 0 grasp candidates.
---------------------------------------------

Do I need mesh to get grasps ?
This is what I get after pressing r

**Comment by atenpas** [comment]
From the output, it looks like the workspace filter removes all points (which should not be happening). Could you upload the pcd file?

**Comment by chaiban** [comment]
Sorry for closing it, I pressed it by mistake.

**Comment by atenpas** [comment]
Have you tried to change the workspace as I suggested above? In `cfg/params.cfg`, set `workspace = -10.0 10.0 -10.0 10.0 -10.0 10.0`.

**Comment by chaiban** [comment]
Yes, this is the result I got, still no grasps. I will try to increase voxelize and try it again.

finger_width: 0.01
hand_outer_diameter: 0.12
hand_depth: 0.06
hand_height: 0.02
init_bite: 0.01
CFG: Not a valid b received!
voxelize: 1
remove_outliers: 0
workspace: -10.0 10.0 -10.0 10.0 -10.0 10.0
camera_pose: 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
num_samples: 5
num_threads: 4
nn_radius: 0.001
num_orientations: 1
rotation_axis: 2
plot_grasps: 1
plot_normals: 1
Loaded point cloud with 1319524 points 
3
Processing cloud with: 1319524 points.
After workspace filtering: 1319524 points left.
After voxelization: 1305987 points left.
Subsampled 5 at random uniformly.
Calculating surface normals ...
camera: 0, #indices: 1305987, #normals: 1305987 
 runtime (normals): 35.6881
Reversing direction of normals that do not point to at least one camera ...
 reversed 0 normals
 runtime (reverse normals): 0.0104546
Drawing 1305987 normals

Estimating local reference frames ...
Estimated 5 local reference frames in 0.0001489 sec.
Finding hand poses ...
 Found 0 grasp candidate sets in 0.0492453 sec.
====> HAND SEARCH TIME: 0.411898
Generated 0 grasp candidate sets.
Generated 0 grasp candidates.

Thank you

**Comment by atenpas** [comment]
Set `num_samples = 500`.

**Comment by chaiban** [comment]
Thank you. It is generating the grasp candidates but the width of the not enough to grasp.

![screenshot from 2019-02-08 09-43-30](https://user-images.githubusercontent.com/38505021/52467902-52213c80-2b87-11e9-9160-8a9ff15b6345.png)

I would like to how to change the work space ? 
How can I change the values (reason for changing ) ?

Thank you.

**Comment by atenpas** [comment]
Your object seems to be quite large in size. Perhaps you should decrease its size.

`hand_outer_diameter` is the parameter to set the width.

**Comment by chaiban** [comment]
Thank you so much for your help!
