### ISSUE TITLE
Approach, binormal, axis vector to Rotation matrix or euler angles

### ISSUE THREAD

**Issue by chaiban** [atenpas/gpg#13]
Hi @atenpas ,

I am able to get grasp candidates for custom pointclouds.
I am missing a point vector to 6D pose conversion. 

According to your work --> Approach vector is x-axis,
                                           binormal is y-axis,
                                           axis is z-axis are 3D vectors. Is it the same as rotation matrix ? 
rotation matrix = array[ x vector, y-vector, and z-vector] ?

is this correct ? I think I am missing a point.

Thank you! please suggest if i am work.

**Comment by atenpas** [comment]
This visualization might help: https://raw.githubusercontent.com/atenpas/gpd/master/readme/hand_frame.png. Yes, the ordering is correct for GPD. And yes, if you put those vectors as columns in a matrix, it should result in a valid rotation matrix.

Note that when using this with a robot, what the axes mean depends on the convention of your robot hand, ROS etc. For example, the z-vector might be the approach axis.

**Comment by chaiban** [comment]
Hi @atenpas 
Thank you so much it is clear!
