### ISSUE TITLE
Support for PCL GPU?

### ISSUE THREAD

**Issue by atyshka** [atenpas/gpg#3]
PCL supports GPU optimization for normal estimation in [this](http://docs.pointclouds.org/1.8.1/classpcl_1_1gpu_1_1_normal_estimation.html#a6912e30c3eab27c22d7aca72ae71f7ef) class. It's a pretty simple change, the interface is pretty much the same. Would you want to make a branch and implement it yourself or create a pull request?

**Comment by atenpas** [comment]
Why do you need this? Just for speed? Also, it requires compiling PCL manually.
